# Generated by Django 4.2.6 on 2023-11-13 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compani', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('image', models.ImageField(upload_to='images/')),
                ('text', models.TextField()),
                ('money', models.IntegerField(default=0)),
                ('producers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producers', to='server.producers')),
            ],
        ),
    ]
