# Generated by Django 4.2.6 on 2023-12-03 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_alter_goods_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('tovarId', models.IntegerField()),
                ('name', models.CharField(max_length=64)),
                ('producers', models.CharField(max_length=20)),
                ('money', models.IntegerField()),
            ],
        ),
    ]
