# Generated by Django 4.2.6 on 2023-12-06 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='tovarId',
            field=models.IntegerField(default=1),
        ),
    ]
